project_id = "rhrrvaggaubvqrbsqjbv"

[functions.generate-recipes]
verify_jwt = false

[functions.generate-dessert-recipes]
verify_jwt = false

[functions.generate-recipe-ai]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false